<?php

namespace ContactboxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhonenumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhonenumberRepository extends EntityRepository
{
}
